language: ruby
sudo: required
services:
  - docker
rvm:
- 2.3.3
env:
  - RAILS_ENV=test
script:
  - ./build.sh
deploy:
  provider: heroku
  app: grocer-web
  api_key:
    secure: s3SLyA8Ac+7Xw1fxAme2Ax3ux/pCrITuhvYIYqwBZZdxMwZQKEfFanAyX/v+AQnBNegSIgZ7SnLHwJ1JBzEp9D/DSPy6bo6yeM4gGzTNWc9sxqDiMczwOfJ0ltqkGpPyjMlICdW9mcRWIrrAZb5bOU1n/n3rPDwWubXDRs44wdVPehZj7LCutQnMoJiHXhK+seUEdxO2l7NBGE2yaEEO7oGMzI+ghWhnlKdG6BkaRh2UGgO1k4jcpDbWUIHCBotOn+uobS5z6ZYu7mePf5p+WJxU9kYON5QT6OfGeOf/CliTlBhCjykDC3zaMOUJG/mdTXk5qIN7JfQv1vEwx8Lm36mTaFGMK2BlCxcysG38luBGW28On1bOTUWph5M9r3Hi78s1uBT29RcEBukuHh9S1pdKutaJ9s82FacylgwZME1//BwVQHj639mxzQ+dK2te/FVSjKmNxE5HHCMFJgQIY3H+cZg2xpqQ9BZJQ5ImWyY3eB9hMkZV5Gb0WExYmCzbne84+iNR+WJuColIsgxisBSEJoMosMTUkerFkI3XbS1wuL3Lje0g+s97d9SP+dZaaUXGw1pj+JAoWclcmaK0EQn6VkiX0n9fVHoGa2nuG66cwNr0hiPzsUfaObC871CQYJ/WGQ7QrusG5kd4JB3c0khz/SgnQkaX9jCtWbPvJn8=
