version: '2'
services:
  neo-dev:
    image: neo4j:3.2.2
    environment:
      - NEO4J_AUTH=none
    ports:
      - "7474:7474"
      - "7687:7687"
  neo-test:
    image: neo4j:3.2.2
    environment:
      - NEO4J_AUTH=none
      - DBMS.CONNECTOR_BOLT=7688
    ports:
      - "7575:7474"
      - "7688:7688"
